micronaut.application.name=community-map-api

datasources.default.url=jdbc:postgresql://localhost:5433/community_map
datasources.default.username=community_map
datasources.default.password=community_map
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES

flyway.datasources.default.enabled=true

micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins=http://localhost:5173
micronaut.server.cors.configurations.web.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
micronaut.server.cors.configurations.web.allowed-headers=Content-Type,Authorization